FROM 786796192785.dkr.ecr.eu-west-1.amazonaws.com/10x/10x-openjdk-11-ssm:latest
ADD . /src
WORKDIR /src
RUN ./gradlew --version
RUN ./gradlew --no-daemon --parallel --configure-on-demand clean compileJava --stacktrace --quiet
